apiVersion: apps/v1
kind: Deployment
metadata:
  name: certbot1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-certbot-container
        image: nginx:latest
        ports:
        - containerPort: 80

      - name: certbot-container
        image: certbot:latest
        ports:
        - containerPort: 8081
